FROM tomcat:latest
RUN cp -R /usr/local/tomcat/webapps.dist/* /usr/local/tomcat/webapps
# RUN cp /root/COSC2767_Assignment1_BashScript_AWS_s3801962/client2/s3801962_web/target/s3801962_web.war /opt/tomcat/webapps/

